import type { Account, Athlete, Event, Group } from "./types";

export const groups: Group[] = [
  { id: "adult", name: "Adulto", schedule: "Seg/Qua" },
  { id: "child", name: "Infantil iniciante", schedule: "Seg/Qua/Sex" },
  { id: "juvenile", name: "Juvenil", schedule: "Ter/Qui" },
];
export const events: Event[] = [
  {
    id: "parents",
    name: "Reunião de Pais - Setembro",
    date: "20/09/2026 às 18:00",
    location: "CT Arte Suave",
    kind: "meeting",
  },
  {
    id: "championship",
    name: "Campeonato Regional de Jiu-Jitsu",
    date: "27/09/2026 às 18:00",
    location: "CT Arte Suave",
    kind: "championship",
  },
];
export const seedAthletes: Athlete[] = [
  {
    id: "anna",
    accountId: "athlete",
    name: "Anna Beatryz",
    birthDate: "05/09/2006",
    emails: ["annabeatryz@artesuave.com"],
    phones: [],
    groupId: "adult",
    belt: "Branca",
    attendance: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
    ],
    active: true,
  },
  {
    id: "joao",
    guardianId: "responsible",
    name: "João Neto",
    birthDate: "10/03/2016",
    emails: [],
    phones: [],
    groupId: "child",
    belt: "Branca",
    attendance: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
    ],
    active: true,
  },
  {
    id: "juliana",
    accountId: "inactive",
    name: "Juliana Alves",
    birthDate: "10/01/2003",
    emails: ["julianaalves@artesuave.com"],
    phones: [],
    groupId: "adult",
    belt: "Branca",
    attendance: [],
    active: true,
  },
];
export const seedAccounts: Account[] = [
  {
    id: "superadmin",
    name: "Gestor do Projeto",
    birthDate: "10/01/1980",
    emails: ["gestor@artesuave.com"],
    phones: [],
    role: "admin",
    active: true,
    isSuperAdmin: true,
    athleteIds: [],
  },
  {
    id: "admin",
    name: "Ana Coordenadora",
    birthDate: "10/02/1985",
    emails: ["ana@artesuave.com"],
    phones: [],
    role: "admin",
    active: true,
    isSuperAdmin: false,
    athleteIds: [],
  },
  {
    id: "responsible",
    name: "Paulo José",
    birthDate: "12/06/1980",
    emails: ["paulojose@artesuave.com"],
    phones: [],
    role: "responsible",
    active: true,
    isSuperAdmin: false,
    athleteIds: ["joao"],
  },
  {
    id: "athlete",
    name: "Anna Beatryz",
    birthDate: "05/09/2006",
    emails: ["annabeatryz@artesuave.com"],
    phones: [],
    role: "athlete",
    active: true,
    isSuperAdmin: false,
    athleteIds: ["anna"],
  },
  {
    id: "inactive",
    name: "Juliana Alves",
    birthDate: "10/01/2003",
    emails: ["julianaalves@artesuave.com"],
    phones: [],
    role: "athlete",
    active: false,
    isSuperAdmin: false,
    athleteIds: ["juliana"],
  },
];
